version: '3.9'

services:
  db:
    image: postgres
    restart: always
    hostname: localhost
    ports:
      - '5432:5432'
    volumes:
      - farm-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
volumes:
  farm-data:
