version: '3.9'

services:
  db:
    image: postgres
    restart: always
    hostname: localhost
    ports:
      - "5432:5432"
    volumes:
       - postgres-data:/var/lib/postgresql/dev
    environment:
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dev
volumes:
  postgres-data: